//**************************************************************
//Common Gen2 Client Messages Defined
//**************************************************************

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v3.21.12
// source: commonClientMessages.proto

package ned

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ResponseCode int32

const (
	ResponseCode_RESPONSE_UNKNOWN       ResponseCode = 0
	ResponseCode_RESPONSE_OK            ResponseCode = 1
	ResponseCode_RESPONSE_COMMAND_ERROR ResponseCode = -1
	ResponseCode_RESPONSE_BAD_REQUEST   ResponseCode = -2
)

// Enum value maps for ResponseCode.
var (
	ResponseCode_name = map[int32]string{
		0:  "RESPONSE_UNKNOWN",
		1:  "RESPONSE_OK",
		-1: "RESPONSE_COMMAND_ERROR",
		-2: "RESPONSE_BAD_REQUEST",
	}
	ResponseCode_value = map[string]int32{
		"RESPONSE_UNKNOWN":       0,
		"RESPONSE_OK":            1,
		"RESPONSE_COMMAND_ERROR": -1,
		"RESPONSE_BAD_REQUEST":   -2,
	}
)

func (x ResponseCode) Enum() *ResponseCode {
	p := new(ResponseCode)
	*p = x
	return p
}

func (x ResponseCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ResponseCode) Descriptor() protoreflect.EnumDescriptor {
	return file_commonClientMessages_proto_enumTypes[0].Descriptor()
}

func (ResponseCode) Type() protoreflect.EnumType {
	return &file_commonClientMessages_proto_enumTypes[0]
}

func (x ResponseCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ResponseCode.Descriptor instead.
func (ResponseCode) EnumDescriptor() ([]byte, []int) {
	return file_commonClientMessages_proto_rawDescGZIP(), []int{0}
}

type CommonRequestPayloads struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to RequestType:
	//
	//	*CommonRequestPayloads_FactoryReset
	//	*CommonRequestPayloads_FindMe
	//	*CommonRequestPayloads_ForgetCore
	//	*CommonRequestPayloads_GetDeviceConfiguration
	//	*CommonRequestPayloads_GetDeviceInformation
	//	*CommonRequestPayloads_PairToCore
	//	*CommonRequestPayloads_SetTelemetryConfiguration
	//	*CommonRequestPayloads_GetTelemetryConfiguration
	//	*CommonRequestPayloads_SetServiceModeStatus
	RequestType   isCommonRequestPayloads_RequestType `protobuf_oneof:"request_type"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommonRequestPayloads) Reset() {
	*x = CommonRequestPayloads{}
	mi := &file_commonClientMessages_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommonRequestPayloads) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommonRequestPayloads) ProtoMessage() {}

func (x *CommonRequestPayloads) ProtoReflect() protoreflect.Message {
	mi := &file_commonClientMessages_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommonRequestPayloads.ProtoReflect.Descriptor instead.
func (*CommonRequestPayloads) Descriptor() ([]byte, []int) {
	return file_commonClientMessages_proto_rawDescGZIP(), []int{0}
}

func (x *CommonRequestPayloads) GetRequestType() isCommonRequestPayloads_RequestType {
	if x != nil {
		return x.RequestType
	}
	return nil
}

func (x *CommonRequestPayloads) GetFactoryReset() *FactoryResetCmdRequestPayload {
	if x != nil {
		if x, ok := x.RequestType.(*CommonRequestPayloads_FactoryReset); ok {
			return x.FactoryReset
		}
	}
	return nil
}

func (x *CommonRequestPayloads) GetFindMe() *FindMeCmdRequestPayload {
	if x != nil {
		if x, ok := x.RequestType.(*CommonRequestPayloads_FindMe); ok {
			return x.FindMe
		}
	}
	return nil
}

func (x *CommonRequestPayloads) GetForgetCore() *ForgetCoreCmdRequestPayload {
	if x != nil {
		if x, ok := x.RequestType.(*CommonRequestPayloads_ForgetCore); ok {
			return x.ForgetCore
		}
	}
	return nil
}

func (x *CommonRequestPayloads) GetGetDeviceConfiguration() *GetDeviceConfigurationRequestPayload {
	if x != nil {
		if x, ok := x.RequestType.(*CommonRequestPayloads_GetDeviceConfiguration); ok {
			return x.GetDeviceConfiguration
		}
	}
	return nil
}

func (x *CommonRequestPayloads) GetGetDeviceInformation() *GetDeviceInformationRequestPayload {
	if x != nil {
		if x, ok := x.RequestType.(*CommonRequestPayloads_GetDeviceInformation); ok {
			return x.GetDeviceInformation
		}
	}
	return nil
}

func (x *CommonRequestPayloads) GetPairToCore() *PairToCoreCmdRequestPayload {
	if x != nil {
		if x, ok := x.RequestType.(*CommonRequestPayloads_PairToCore); ok {
			return x.PairToCore
		}
	}
	return nil
}

func (x *CommonRequestPayloads) GetSetTelemetryConfiguration() *SetTelemetryConfigurationRequestPayload {
	if x != nil {
		if x, ok := x.RequestType.(*CommonRequestPayloads_SetTelemetryConfiguration); ok {
			return x.SetTelemetryConfiguration
		}
	}
	return nil
}

func (x *CommonRequestPayloads) GetGetTelemetryConfiguration() *GetTelemetryConfigurationRequestPayload {
	if x != nil {
		if x, ok := x.RequestType.(*CommonRequestPayloads_GetTelemetryConfiguration); ok {
			return x.GetTelemetryConfiguration
		}
	}
	return nil
}

func (x *CommonRequestPayloads) GetSetServiceModeStatus() *SetServiceModeStatusRequestPayload {
	if x != nil {
		if x, ok := x.RequestType.(*CommonRequestPayloads_SetServiceModeStatus); ok {
			return x.SetServiceModeStatus
		}
	}
	return nil
}

type isCommonRequestPayloads_RequestType interface {
	isCommonRequestPayloads_RequestType()
}

type CommonRequestPayloads_FactoryReset struct {
	FactoryReset *FactoryResetCmdRequestPayload `protobuf:"bytes,1,opt,name=factory_reset,json=factoryReset,proto3,oneof"`
}

type CommonRequestPayloads_FindMe struct {
	FindMe *FindMeCmdRequestPayload `protobuf:"bytes,2,opt,name=find_me,json=findMe,proto3,oneof"`
}

type CommonRequestPayloads_ForgetCore struct {
	ForgetCore *ForgetCoreCmdRequestPayload `protobuf:"bytes,3,opt,name=forget_core,json=forgetCore,proto3,oneof"`
}

type CommonRequestPayloads_GetDeviceConfiguration struct {
	GetDeviceConfiguration *GetDeviceConfigurationRequestPayload `protobuf:"bytes,4,opt,name=get_device_configuration,json=getDeviceConfiguration,proto3,oneof"`
}

type CommonRequestPayloads_GetDeviceInformation struct {
	GetDeviceInformation *GetDeviceInformationRequestPayload `protobuf:"bytes,5,opt,name=get_device_information,json=getDeviceInformation,proto3,oneof"`
}

type CommonRequestPayloads_PairToCore struct {
	PairToCore *PairToCoreCmdRequestPayload `protobuf:"bytes,6,opt,name=pair_to_core,json=pairToCore,proto3,oneof"`
}

type CommonRequestPayloads_SetTelemetryConfiguration struct {
	SetTelemetryConfiguration *SetTelemetryConfigurationRequestPayload `protobuf:"bytes,7,opt,name=set_telemetry_configuration,json=setTelemetryConfiguration,proto3,oneof"`
}

type CommonRequestPayloads_GetTelemetryConfiguration struct {
	GetTelemetryConfiguration *GetTelemetryConfigurationRequestPayload `protobuf:"bytes,8,opt,name=get_telemetry_configuration,json=getTelemetryConfiguration,proto3,oneof"`
}

type CommonRequestPayloads_SetServiceModeStatus struct {
	SetServiceModeStatus *SetServiceModeStatusRequestPayload `protobuf:"bytes,9,opt,name=set_service_mode_status,json=setServiceModeStatus,proto3,oneof"`
}

func (*CommonRequestPayloads_FactoryReset) isCommonRequestPayloads_RequestType() {}

func (*CommonRequestPayloads_FindMe) isCommonRequestPayloads_RequestType() {}

func (*CommonRequestPayloads_ForgetCore) isCommonRequestPayloads_RequestType() {}

func (*CommonRequestPayloads_GetDeviceConfiguration) isCommonRequestPayloads_RequestType() {}

func (*CommonRequestPayloads_GetDeviceInformation) isCommonRequestPayloads_RequestType() {}

func (*CommonRequestPayloads_PairToCore) isCommonRequestPayloads_RequestType() {}

func (*CommonRequestPayloads_SetTelemetryConfiguration) isCommonRequestPayloads_RequestType() {}

func (*CommonRequestPayloads_GetTelemetryConfiguration) isCommonRequestPayloads_RequestType() {}

func (*CommonRequestPayloads_SetServiceModeStatus) isCommonRequestPayloads_RequestType() {}

type CommonResponsePayloads struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to ResponseType:
	//
	//	*CommonResponsePayloads_GetDeviceConfigurationResponse
	//	*CommonResponsePayloads_GetDeviceInformationResponse
	//	*CommonResponsePayloads_GetTelemetryConfigurationResponse
	ResponseType  isCommonResponsePayloads_ResponseType `protobuf_oneof:"response_type"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommonResponsePayloads) Reset() {
	*x = CommonResponsePayloads{}
	mi := &file_commonClientMessages_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommonResponsePayloads) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommonResponsePayloads) ProtoMessage() {}

func (x *CommonResponsePayloads) ProtoReflect() protoreflect.Message {
	mi := &file_commonClientMessages_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommonResponsePayloads.ProtoReflect.Descriptor instead.
func (*CommonResponsePayloads) Descriptor() ([]byte, []int) {
	return file_commonClientMessages_proto_rawDescGZIP(), []int{1}
}

func (x *CommonResponsePayloads) GetResponseType() isCommonResponsePayloads_ResponseType {
	if x != nil {
		return x.ResponseType
	}
	return nil
}

func (x *CommonResponsePayloads) GetGetDeviceConfigurationResponse() *GetDeviceConfigurationResponsePayload {
	if x != nil {
		if x, ok := x.ResponseType.(*CommonResponsePayloads_GetDeviceConfigurationResponse); ok {
			return x.GetDeviceConfigurationResponse
		}
	}
	return nil
}

func (x *CommonResponsePayloads) GetGetDeviceInformationResponse() *GetDeviceInformationResponsePayload {
	if x != nil {
		if x, ok := x.ResponseType.(*CommonResponsePayloads_GetDeviceInformationResponse); ok {
			return x.GetDeviceInformationResponse
		}
	}
	return nil
}

func (x *CommonResponsePayloads) GetGetTelemetryConfigurationResponse() *GetTelemetryConfigurationResponsePayload {
	if x != nil {
		if x, ok := x.ResponseType.(*CommonResponsePayloads_GetTelemetryConfigurationResponse); ok {
			return x.GetTelemetryConfigurationResponse
		}
	}
	return nil
}

type isCommonResponsePayloads_ResponseType interface {
	isCommonResponsePayloads_ResponseType()
}

type CommonResponsePayloads_GetDeviceConfigurationResponse struct {
	GetDeviceConfigurationResponse *GetDeviceConfigurationResponsePayload `protobuf:"bytes,1,opt,name=get_device_configuration_response,json=getDeviceConfigurationResponse,proto3,oneof"`
}

type CommonResponsePayloads_GetDeviceInformationResponse struct {
	GetDeviceInformationResponse *GetDeviceInformationResponsePayload `protobuf:"bytes,2,opt,name=get_device_information_response,json=getDeviceInformationResponse,proto3,oneof"`
}

type CommonResponsePayloads_GetTelemetryConfigurationResponse struct {
	GetTelemetryConfigurationResponse *GetTelemetryConfigurationResponsePayload `protobuf:"bytes,3,opt,name=get_telemetry_configuration_response,json=getTelemetryConfigurationResponse,proto3,oneof"`
}

func (*CommonResponsePayloads_GetDeviceConfigurationResponse) isCommonResponsePayloads_ResponseType() {
}

func (*CommonResponsePayloads_GetDeviceInformationResponse) isCommonResponsePayloads_ResponseType() {}

func (*CommonResponsePayloads_GetTelemetryConfigurationResponse) isCommonResponsePayloads_ResponseType() {
}

// a command wrapper message with a type field
// MQTT topic: 'cmd/<category>/<serial number>/req'
type CommandRequestMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommandUuid   string                 `protobuf:"bytes,1,opt,name=command_uuid,json=commandUuid,proto3" json:"command_uuid,omitempty"`
	Common        *CommonRequestPayloads `protobuf:"bytes,2,opt,name=common,proto3" json:"common,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandRequestMessage) Reset() {
	*x = CommandRequestMessage{}
	mi := &file_commonClientMessages_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandRequestMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandRequestMessage) ProtoMessage() {}

func (x *CommandRequestMessage) ProtoReflect() protoreflect.Message {
	mi := &file_commonClientMessages_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandRequestMessage.ProtoReflect.Descriptor instead.
func (*CommandRequestMessage) Descriptor() ([]byte, []int) {
	return file_commonClientMessages_proto_rawDescGZIP(), []int{2}
}

func (x *CommandRequestMessage) GetCommandUuid() string {
	if x != nil {
		return x.CommandUuid
	}
	return ""
}

func (x *CommandRequestMessage) GetCommon() *CommonRequestPayloads {
	if x != nil {
		return x.Common
	}
	return nil
}

// a response wrapper message with a message type field
// and the required response code
// MQTT topic: 'cmd/<category>/<serial number>/res'
type CommandResponseMessage struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	CommandUuid string                 `protobuf:"bytes,1,opt,name=command_uuid,json=commandUuid,proto3" json:"command_uuid,omitempty"`
	// required
	ResponseCode  ResponseCode            `protobuf:"varint,2,opt,name=response_code,json=responseCode,proto3,enum=ned.ResponseCode" json:"response_code,omitempty"`
	Common        *CommonResponsePayloads `protobuf:"bytes,3,opt,name=common,proto3" json:"common,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandResponseMessage) Reset() {
	*x = CommandResponseMessage{}
	mi := &file_commonClientMessages_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandResponseMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandResponseMessage) ProtoMessage() {}

func (x *CommandResponseMessage) ProtoReflect() protoreflect.Message {
	mi := &file_commonClientMessages_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandResponseMessage.ProtoReflect.Descriptor instead.
func (*CommandResponseMessage) Descriptor() ([]byte, []int) {
	return file_commonClientMessages_proto_rawDescGZIP(), []int{3}
}

func (x *CommandResponseMessage) GetCommandUuid() string {
	if x != nil {
		return x.CommandUuid
	}
	return ""
}

func (x *CommandResponseMessage) GetResponseCode() ResponseCode {
	if x != nil {
		return x.ResponseCode
	}
	return ResponseCode_RESPONSE_UNKNOWN
}

func (x *CommandResponseMessage) GetCommon() *CommonResponsePayloads {
	if x != nil {
		return x.Common
	}
	return nil
}

var File_commonClientMessages_proto protoreflect.FileDescriptor

const file_commonClientMessages_proto_rawDesc = "" +
	"\n" +
	"\x1acommonClientMessages.proto\x12\x03ned\x1a\x13factory_reset.proto\x1a\rfind_me.proto\x1a\x11forget_core.proto\x1a\x1eget_device_configuration.proto\x1a\x1cget_device_information.proto\x1a\x12pair_to_core.proto\x1a\x1dtelemetry_configuration.proto\x1a\x12service_mode.proto\"\xc0\x06\n" +
	"\x15CommonRequestPayloads\x12I\n" +
	"\rfactory_reset\x18\x01 \x01(\v2\".ned.FactoryResetCmdRequestPayloadH\x00R\ffactoryReset\x127\n" +
	"\afind_me\x18\x02 \x01(\v2\x1c.ned.FindMeCmdRequestPayloadH\x00R\x06findMe\x12C\n" +
	"\vforget_core\x18\x03 \x01(\v2 .ned.ForgetCoreCmdRequestPayloadH\x00R\n" +
	"forgetCore\x12e\n" +
	"\x18get_device_configuration\x18\x04 \x01(\v2).ned.GetDeviceConfigurationRequestPayloadH\x00R\x16getDeviceConfiguration\x12_\n" +
	"\x16get_device_information\x18\x05 \x01(\v2'.ned.GetDeviceInformationRequestPayloadH\x00R\x14getDeviceInformation\x12D\n" +
	"\fpair_to_core\x18\x06 \x01(\v2 .ned.PairToCoreCmdRequestPayloadH\x00R\n" +
	"pairToCore\x12n\n" +
	"\x1bset_telemetry_configuration\x18\a \x01(\v2,.ned.SetTelemetryConfigurationRequestPayloadH\x00R\x19setTelemetryConfiguration\x12n\n" +
	"\x1bget_telemetry_configuration\x18\b \x01(\v2,.ned.GetTelemetryConfigurationRequestPayloadH\x00R\x19getTelemetryConfiguration\x12`\n" +
	"\x17set_service_mode_status\x18\t \x01(\v2'.ned.SetServiceModeStatusRequestPayloadH\x00R\x14setServiceModeStatusB\x0e\n" +
	"\frequest_type\"\x98\x03\n" +
	"\x16CommonResponsePayloads\x12w\n" +
	"!get_device_configuration_response\x18\x01 \x01(\v2*.ned.GetDeviceConfigurationResponsePayloadH\x00R\x1egetDeviceConfigurationResponse\x12q\n" +
	"\x1fget_device_information_response\x18\x02 \x01(\v2(.ned.GetDeviceInformationResponsePayloadH\x00R\x1cgetDeviceInformationResponse\x12\x80\x01\n" +
	"$get_telemetry_configuration_response\x18\x03 \x01(\v2-.ned.GetTelemetryConfigurationResponsePayloadH\x00R!getTelemetryConfigurationResponseB\x0f\n" +
	"\rresponse_type\"n\n" +
	"\x15CommandRequestMessage\x12!\n" +
	"\fcommand_uuid\x18\x01 \x01(\tR\vcommandUuid\x122\n" +
	"\x06common\x18\x02 \x01(\v2\x1a.ned.CommonRequestPayloadsR\x06common\"\xa8\x01\n" +
	"\x16CommandResponseMessage\x12!\n" +
	"\fcommand_uuid\x18\x01 \x01(\tR\vcommandUuid\x126\n" +
	"\rresponse_code\x18\x02 \x01(\x0e2\x11.ned.ResponseCodeR\fresponseCode\x123\n" +
	"\x06common\x18\x03 \x01(\v2\x1b.ned.CommonResponsePayloadsR\x06common*}\n" +
	"\fResponseCode\x12\x14\n" +
	"\x10RESPONSE_UNKNOWN\x10\x00\x12\x0f\n" +
	"\vRESPONSE_OK\x10\x01\x12#\n" +
	"\x16RESPONSE_COMMAND_ERROR\x10\xff\xff\xff\xff\xff\xff\xff\xff\xff\x01\x12!\n" +
	"\x14RESPONSE_BAD_REQUEST\x10\xfe\xff\xff\xff\xff\xff\xff\xff\xff\x01B\x11Z\x0fpooltester3/nedb\x06proto3"

var (
	file_commonClientMessages_proto_rawDescOnce sync.Once
	file_commonClientMessages_proto_rawDescData []byte
)

func file_commonClientMessages_proto_rawDescGZIP() []byte {
	file_commonClientMessages_proto_rawDescOnce.Do(func() {
		file_commonClientMessages_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_commonClientMessages_proto_rawDesc), len(file_commonClientMessages_proto_rawDesc)))
	})
	return file_commonClientMessages_proto_rawDescData
}

var file_commonClientMessages_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_commonClientMessages_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_commonClientMessages_proto_goTypes = []any{
	(ResponseCode)(0),                                // 0: ned.ResponseCode
	(*CommonRequestPayloads)(nil),                    // 1: ned.CommonRequestPayloads
	(*CommonResponsePayloads)(nil),                   // 2: ned.CommonResponsePayloads
	(*CommandRequestMessage)(nil),                    // 3: ned.CommandRequestMessage
	(*CommandResponseMessage)(nil),                   // 4: ned.CommandResponseMessage
	(*FactoryResetCmdRequestPayload)(nil),            // 5: ned.FactoryResetCmdRequestPayload
	(*FindMeCmdRequestPayload)(nil),                  // 6: ned.FindMeCmdRequestPayload
	(*ForgetCoreCmdRequestPayload)(nil),              // 7: ned.ForgetCoreCmdRequestPayload
	(*GetDeviceConfigurationRequestPayload)(nil),     // 8: ned.GetDeviceConfigurationRequestPayload
	(*GetDeviceInformationRequestPayload)(nil),       // 9: ned.GetDeviceInformationRequestPayload
	(*PairToCoreCmdRequestPayload)(nil),              // 10: ned.PairToCoreCmdRequestPayload
	(*SetTelemetryConfigurationRequestPayload)(nil),  // 11: ned.SetTelemetryConfigurationRequestPayload
	(*GetTelemetryConfigurationRequestPayload)(nil),  // 12: ned.GetTelemetryConfigurationRequestPayload
	(*SetServiceModeStatusRequestPayload)(nil),       // 13: ned.SetServiceModeStatusRequestPayload
	(*GetDeviceConfigurationResponsePayload)(nil),    // 14: ned.GetDeviceConfigurationResponsePayload
	(*GetDeviceInformationResponsePayload)(nil),      // 15: ned.GetDeviceInformationResponsePayload
	(*GetTelemetryConfigurationResponsePayload)(nil), // 16: ned.GetTelemetryConfigurationResponsePayload
}
var file_commonClientMessages_proto_depIdxs = []int32{
	5,  // 0: ned.CommonRequestPayloads.factory_reset:type_name -> ned.FactoryResetCmdRequestPayload
	6,  // 1: ned.CommonRequestPayloads.find_me:type_name -> ned.FindMeCmdRequestPayload
	7,  // 2: ned.CommonRequestPayloads.forget_core:type_name -> ned.ForgetCoreCmdRequestPayload
	8,  // 3: ned.CommonRequestPayloads.get_device_configuration:type_name -> ned.GetDeviceConfigurationRequestPayload
	9,  // 4: ned.CommonRequestPayloads.get_device_information:type_name -> ned.GetDeviceInformationRequestPayload
	10, // 5: ned.CommonRequestPayloads.pair_to_core:type_name -> ned.PairToCoreCmdRequestPayload
	11, // 6: ned.CommonRequestPayloads.set_telemetry_configuration:type_name -> ned.SetTelemetryConfigurationRequestPayload
	12, // 7: ned.CommonRequestPayloads.get_telemetry_configuration:type_name -> ned.GetTelemetryConfigurationRequestPayload
	13, // 8: ned.CommonRequestPayloads.set_service_mode_status:type_name -> ned.SetServiceModeStatusRequestPayload
	14, // 9: ned.CommonResponsePayloads.get_device_configuration_response:type_name -> ned.GetDeviceConfigurationResponsePayload
	15, // 10: ned.CommonResponsePayloads.get_device_information_response:type_name -> ned.GetDeviceInformationResponsePayload
	16, // 11: ned.CommonResponsePayloads.get_telemetry_configuration_response:type_name -> ned.GetTelemetryConfigurationResponsePayload
	1,  // 12: ned.CommandRequestMessage.common:type_name -> ned.CommonRequestPayloads
	0,  // 13: ned.CommandResponseMessage.response_code:type_name -> ned.ResponseCode
	2,  // 14: ned.CommandResponseMessage.common:type_name -> ned.CommonResponsePayloads
	15, // [15:15] is the sub-list for method output_type
	15, // [15:15] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_commonClientMessages_proto_init() }
func file_commonClientMessages_proto_init() {
	if File_commonClientMessages_proto != nil {
		return
	}
	file_factory_reset_proto_init()
	file_find_me_proto_init()
	file_forget_core_proto_init()
	file_get_device_configuration_proto_init()
	file_get_device_information_proto_init()
	file_pair_to_core_proto_init()
	file_telemetry_configuration_proto_init()
	file_service_mode_proto_init()
	file_commonClientMessages_proto_msgTypes[0].OneofWrappers = []any{
		(*CommonRequestPayloads_FactoryReset)(nil),
		(*CommonRequestPayloads_FindMe)(nil),
		(*CommonRequestPayloads_ForgetCore)(nil),
		(*CommonRequestPayloads_GetDeviceConfiguration)(nil),
		(*CommonRequestPayloads_GetDeviceInformation)(nil),
		(*CommonRequestPayloads_PairToCore)(nil),
		(*CommonRequestPayloads_SetTelemetryConfiguration)(nil),
		(*CommonRequestPayloads_GetTelemetryConfiguration)(nil),
		(*CommonRequestPayloads_SetServiceModeStatus)(nil),
	}
	file_commonClientMessages_proto_msgTypes[1].OneofWrappers = []any{
		(*CommonResponsePayloads_GetDeviceConfigurationResponse)(nil),
		(*CommonResponsePayloads_GetDeviceInformationResponse)(nil),
		(*CommonResponsePayloads_GetTelemetryConfigurationResponse)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_commonClientMessages_proto_rawDesc), len(file_commonClientMessages_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_commonClientMessages_proto_goTypes,
		DependencyIndexes: file_commonClientMessages_proto_depIdxs,
		EnumInfos:         file_commonClientMessages_proto_enumTypes,
		MessageInfos:      file_commonClientMessages_proto_msgTypes,
	}.Build()
	File_commonClientMessages_proto = out.File
	file_commonClientMessages_proto_goTypes = nil
	file_commonClientMessages_proto_depIdxs = nil
}
