//**************************************************************
//Get Device Configuration Message proto file
//- command/response definition
//**************************************************************

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v3.21.12
// source: get_device_configuration.proto

package ned

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetDeviceConfigurationRequestPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDeviceConfigurationRequestPayload) Reset() {
	*x = GetDeviceConfigurationRequestPayload{}
	mi := &file_get_device_configuration_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDeviceConfigurationRequestPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDeviceConfigurationRequestPayload) ProtoMessage() {}

func (x *GetDeviceConfigurationRequestPayload) ProtoReflect() protoreflect.Message {
	mi := &file_get_device_configuration_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDeviceConfigurationRequestPayload.ProtoReflect.Descriptor instead.
func (*GetDeviceConfigurationRequestPayload) Descriptor() ([]byte, []int) {
	return file_get_device_configuration_proto_rawDescGZIP(), []int{0}
}

type GetDeviceConfigurationResponsePayload struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CoreBssid      string                 `protobuf:"bytes,1,opt,name=core_bssid,json=coreBssid,proto3" json:"core_bssid,omitempty"`                     // Core BSSID only if the current bus is wifi, otherwise an empty string
	IsFindMeActive bool                   `protobuf:"varint,2,opt,name=is_find_me_active,json=isFindMeActive,proto3" json:"is_find_me_active,omitempty"` // True if find me is active, false otherwise
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetDeviceConfigurationResponsePayload) Reset() {
	*x = GetDeviceConfigurationResponsePayload{}
	mi := &file_get_device_configuration_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDeviceConfigurationResponsePayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDeviceConfigurationResponsePayload) ProtoMessage() {}

func (x *GetDeviceConfigurationResponsePayload) ProtoReflect() protoreflect.Message {
	mi := &file_get_device_configuration_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDeviceConfigurationResponsePayload.ProtoReflect.Descriptor instead.
func (*GetDeviceConfigurationResponsePayload) Descriptor() ([]byte, []int) {
	return file_get_device_configuration_proto_rawDescGZIP(), []int{1}
}

func (x *GetDeviceConfigurationResponsePayload) GetCoreBssid() string {
	if x != nil {
		return x.CoreBssid
	}
	return ""
}

func (x *GetDeviceConfigurationResponsePayload) GetIsFindMeActive() bool {
	if x != nil {
		return x.IsFindMeActive
	}
	return false
}

var File_get_device_configuration_proto protoreflect.FileDescriptor

const file_get_device_configuration_proto_rawDesc = "" +
	"\n" +
	"\x1eget_device_configuration.proto\x12\x03ned\"&\n" +
	"$GetDeviceConfigurationRequestPayload\"q\n" +
	"%GetDeviceConfigurationResponsePayload\x12\x1d\n" +
	"\n" +
	"core_bssid\x18\x01 \x01(\tR\tcoreBssid\x12)\n" +
	"\x11is_find_me_active\x18\x02 \x01(\bR\x0eisFindMeActiveB\x11Z\x0fpooltester3/nedb\x06proto3"

var (
	file_get_device_configuration_proto_rawDescOnce sync.Once
	file_get_device_configuration_proto_rawDescData []byte
)

func file_get_device_configuration_proto_rawDescGZIP() []byte {
	file_get_device_configuration_proto_rawDescOnce.Do(func() {
		file_get_device_configuration_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_get_device_configuration_proto_rawDesc), len(file_get_device_configuration_proto_rawDesc)))
	})
	return file_get_device_configuration_proto_rawDescData
}

var file_get_device_configuration_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_get_device_configuration_proto_goTypes = []any{
	(*GetDeviceConfigurationRequestPayload)(nil),  // 0: ned.GetDeviceConfigurationRequestPayload
	(*GetDeviceConfigurationResponsePayload)(nil), // 1: ned.GetDeviceConfigurationResponsePayload
}
var file_get_device_configuration_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_get_device_configuration_proto_init() }
func file_get_device_configuration_proto_init() {
	if File_get_device_configuration_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_get_device_configuration_proto_rawDesc), len(file_get_device_configuration_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_get_device_configuration_proto_goTypes,
		DependencyIndexes: file_get_device_configuration_proto_depIdxs,
		MessageInfos:      file_get_device_configuration_proto_msgTypes,
	}.Build()
	File_get_device_configuration_proto = out.File
	file_get_device_configuration_proto_goTypes = nil
	file_get_device_configuration_proto_depIdxs = nil
}
