//**************************************************************
//Find Me Message proto file
//- command/response definition
//**************************************************************

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.12.4
// source: find_me.proto

package ned

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FindMeCmdRequestPayload struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	FindMeDurationSeconds string                 `protobuf:"bytes,1,opt,name=find_me_duration_seconds,json=findMeDurationSeconds,proto3" json:"find_me_duration_seconds,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *FindMeCmdRequestPayload) Reset() {
	*x = FindMeCmdRequestPayload{}
	mi := &file_find_me_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindMeCmdRequestPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindMeCmdRequestPayload) ProtoMessage() {}

func (x *FindMeCmdRequestPayload) ProtoReflect() protoreflect.Message {
	mi := &file_find_me_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindMeCmdRequestPayload.ProtoReflect.Descriptor instead.
func (*FindMeCmdRequestPayload) Descriptor() ([]byte, []int) {
	return file_find_me_proto_rawDescGZIP(), []int{0}
}

func (x *FindMeCmdRequestPayload) GetFindMeDurationSeconds() string {
	if x != nil {
		return x.FindMeDurationSeconds
	}
	return ""
}

var File_find_me_proto protoreflect.FileDescriptor

const file_find_me_proto_rawDesc = "" +
	"\n" +
	"\rfind_me.proto\x12\x03ned\"R\n" +
	"\x17FindMeCmdRequestPayload\x127\n" +
	"\x18find_me_duration_seconds\x18\x01 \x01(\tR\x15findMeDurationSecondsB\x1aZ\x18pooltester3_20250916/nedb\x06proto3"

var (
	file_find_me_proto_rawDescOnce sync.Once
	file_find_me_proto_rawDescData []byte
)

func file_find_me_proto_rawDescGZIP() []byte {
	file_find_me_proto_rawDescOnce.Do(func() {
		file_find_me_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_find_me_proto_rawDesc), len(file_find_me_proto_rawDesc)))
	})
	return file_find_me_proto_rawDescData
}

var file_find_me_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_find_me_proto_goTypes = []any{
	(*FindMeCmdRequestPayload)(nil), // 0: ned.FindMeCmdRequestPayload
}
var file_find_me_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_find_me_proto_init() }
func file_find_me_proto_init() {
	if File_find_me_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_find_me_proto_rawDesc), len(file_find_me_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_find_me_proto_goTypes,
		DependencyIndexes: file_find_me_proto_depIdxs,
		MessageInfos:      file_find_me_proto_msgTypes,
	}.Build()
	File_find_me_proto = out.File
	file_find_me_proto_goTypes = nil
	file_find_me_proto_depIdxs = nil
}
