//**************************************************************
//Telemetry Configuration Message proto file
//- command/response definition
//**************************************************************

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.12.4
// source: telemetry_configuration.proto

package ned

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SetTelemetryConfigurationRequestPayload struct {
	state                       protoimpl.MessageState `protogen:"open.v1"`
	TelemetryPeriodValueSeconds int32                  `protobuf:"varint,1,opt,name=telemetry_period_value_seconds,json=telemetryPeriodValueSeconds,proto3" json:"telemetry_period_value_seconds,omitempty"`
	TelemetryEnabled            bool                   `protobuf:"varint,2,opt,name=telemetry_enabled,json=telemetryEnabled,proto3" json:"telemetry_enabled,omitempty"`
	unknownFields               protoimpl.UnknownFields
	sizeCache                   protoimpl.SizeCache
}

func (x *SetTelemetryConfigurationRequestPayload) Reset() {
	*x = SetTelemetryConfigurationRequestPayload{}
	mi := &file_telemetry_configuration_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetTelemetryConfigurationRequestPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetTelemetryConfigurationRequestPayload) ProtoMessage() {}

func (x *SetTelemetryConfigurationRequestPayload) ProtoReflect() protoreflect.Message {
	mi := &file_telemetry_configuration_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetTelemetryConfigurationRequestPayload.ProtoReflect.Descriptor instead.
func (*SetTelemetryConfigurationRequestPayload) Descriptor() ([]byte, []int) {
	return file_telemetry_configuration_proto_rawDescGZIP(), []int{0}
}

func (x *SetTelemetryConfigurationRequestPayload) GetTelemetryPeriodValueSeconds() int32 {
	if x != nil {
		return x.TelemetryPeriodValueSeconds
	}
	return 0
}

func (x *SetTelemetryConfigurationRequestPayload) GetTelemetryEnabled() bool {
	if x != nil {
		return x.TelemetryEnabled
	}
	return false
}

type GetTelemetryConfigurationRequestPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTelemetryConfigurationRequestPayload) Reset() {
	*x = GetTelemetryConfigurationRequestPayload{}
	mi := &file_telemetry_configuration_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTelemetryConfigurationRequestPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTelemetryConfigurationRequestPayload) ProtoMessage() {}

func (x *GetTelemetryConfigurationRequestPayload) ProtoReflect() protoreflect.Message {
	mi := &file_telemetry_configuration_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTelemetryConfigurationRequestPayload.ProtoReflect.Descriptor instead.
func (*GetTelemetryConfigurationRequestPayload) Descriptor() ([]byte, []int) {
	return file_telemetry_configuration_proto_rawDescGZIP(), []int{1}
}

type GetTelemetryConfigurationResponsePayload struct {
	state                       protoimpl.MessageState `protogen:"open.v1"`
	TelemetryPeriodValueSeconds int32                  `protobuf:"varint,1,opt,name=telemetry_period_value_seconds,json=telemetryPeriodValueSeconds,proto3" json:"telemetry_period_value_seconds,omitempty"`
	TelemetryEnabled            bool                   `protobuf:"varint,2,opt,name=telemetry_enabled,json=telemetryEnabled,proto3" json:"telemetry_enabled,omitempty"`
	unknownFields               protoimpl.UnknownFields
	sizeCache                   protoimpl.SizeCache
}

func (x *GetTelemetryConfigurationResponsePayload) Reset() {
	*x = GetTelemetryConfigurationResponsePayload{}
	mi := &file_telemetry_configuration_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTelemetryConfigurationResponsePayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTelemetryConfigurationResponsePayload) ProtoMessage() {}

func (x *GetTelemetryConfigurationResponsePayload) ProtoReflect() protoreflect.Message {
	mi := &file_telemetry_configuration_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTelemetryConfigurationResponsePayload.ProtoReflect.Descriptor instead.
func (*GetTelemetryConfigurationResponsePayload) Descriptor() ([]byte, []int) {
	return file_telemetry_configuration_proto_rawDescGZIP(), []int{2}
}

func (x *GetTelemetryConfigurationResponsePayload) GetTelemetryPeriodValueSeconds() int32 {
	if x != nil {
		return x.TelemetryPeriodValueSeconds
	}
	return 0
}

func (x *GetTelemetryConfigurationResponsePayload) GetTelemetryEnabled() bool {
	if x != nil {
		return x.TelemetryEnabled
	}
	return false
}

var File_telemetry_configuration_proto protoreflect.FileDescriptor

const file_telemetry_configuration_proto_rawDesc = "" +
	"\n" +
	"\x1dtelemetry_configuration.proto\x12\x03ned\"\x9b\x01\n" +
	"'SetTelemetryConfigurationRequestPayload\x12C\n" +
	"\x1etelemetry_period_value_seconds\x18\x01 \x01(\x05R\x1btelemetryPeriodValueSeconds\x12+\n" +
	"\x11telemetry_enabled\x18\x02 \x01(\bR\x10telemetryEnabled\")\n" +
	"'GetTelemetryConfigurationRequestPayload\"\x9c\x01\n" +
	"(GetTelemetryConfigurationResponsePayload\x12C\n" +
	"\x1etelemetry_period_value_seconds\x18\x01 \x01(\x05R\x1btelemetryPeriodValueSeconds\x12+\n" +
	"\x11telemetry_enabled\x18\x02 \x01(\bR\x10telemetryEnabledB\x1aZ\x18pooltester3_20250916/nedb\x06proto3"

var (
	file_telemetry_configuration_proto_rawDescOnce sync.Once
	file_telemetry_configuration_proto_rawDescData []byte
)

func file_telemetry_configuration_proto_rawDescGZIP() []byte {
	file_telemetry_configuration_proto_rawDescOnce.Do(func() {
		file_telemetry_configuration_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_telemetry_configuration_proto_rawDesc), len(file_telemetry_configuration_proto_rawDesc)))
	})
	return file_telemetry_configuration_proto_rawDescData
}

var file_telemetry_configuration_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_telemetry_configuration_proto_goTypes = []any{
	(*SetTelemetryConfigurationRequestPayload)(nil),  // 0: ned.SetTelemetryConfigurationRequestPayload
	(*GetTelemetryConfigurationRequestPayload)(nil),  // 1: ned.GetTelemetryConfigurationRequestPayload
	(*GetTelemetryConfigurationResponsePayload)(nil), // 2: ned.GetTelemetryConfigurationResponsePayload
}
var file_telemetry_configuration_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_telemetry_configuration_proto_init() }
func file_telemetry_configuration_proto_init() {
	if File_telemetry_configuration_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_telemetry_configuration_proto_rawDesc), len(file_telemetry_configuration_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_telemetry_configuration_proto_goTypes,
		DependencyIndexes: file_telemetry_configuration_proto_depIdxs,
		MessageInfos:      file_telemetry_configuration_proto_msgTypes,
	}.Build()
	File_telemetry_configuration_proto = out.File
	file_telemetry_configuration_proto_goTypes = nil
	file_telemetry_configuration_proto_depIdxs = nil
}
