//**************************************************************
//Pair To Core Message proto file
//- command/response definition
//**************************************************************

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.12.4
// source: pair_to_core.proto

package ned

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PairToCoreCmdRequestPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CoreBssid     string                 `protobuf:"bytes,1,opt,name=core_bssid,json=coreBssid,proto3" json:"core_bssid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PairToCoreCmdRequestPayload) Reset() {
	*x = PairToCoreCmdRequestPayload{}
	mi := &file_pair_to_core_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PairToCoreCmdRequestPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PairToCoreCmdRequestPayload) ProtoMessage() {}

func (x *PairToCoreCmdRequestPayload) ProtoReflect() protoreflect.Message {
	mi := &file_pair_to_core_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PairToCoreCmdRequestPayload.ProtoReflect.Descriptor instead.
func (*PairToCoreCmdRequestPayload) Descriptor() ([]byte, []int) {
	return file_pair_to_core_proto_rawDescGZIP(), []int{0}
}

func (x *PairToCoreCmdRequestPayload) GetCoreBssid() string {
	if x != nil {
		return x.CoreBssid
	}
	return ""
}

var File_pair_to_core_proto protoreflect.FileDescriptor

const file_pair_to_core_proto_rawDesc = "" +
	"\n" +
	"\x12pair_to_core.proto\x12\x03ned\"<\n" +
	"\x1bPairToCoreCmdRequestPayload\x12\x1d\n" +
	"\n" +
	"core_bssid\x18\x01 \x01(\tR\tcoreBssidB\x1aZ\x18pooltester3_20250916/nedb\x06proto3"

var (
	file_pair_to_core_proto_rawDescOnce sync.Once
	file_pair_to_core_proto_rawDescData []byte
)

func file_pair_to_core_proto_rawDescGZIP() []byte {
	file_pair_to_core_proto_rawDescOnce.Do(func() {
		file_pair_to_core_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pair_to_core_proto_rawDesc), len(file_pair_to_core_proto_rawDesc)))
	})
	return file_pair_to_core_proto_rawDescData
}

var file_pair_to_core_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_pair_to_core_proto_goTypes = []any{
	(*PairToCoreCmdRequestPayload)(nil), // 0: ned.PairToCoreCmdRequestPayload
}
var file_pair_to_core_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pair_to_core_proto_init() }
func file_pair_to_core_proto_init() {
	if File_pair_to_core_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pair_to_core_proto_rawDesc), len(file_pair_to_core_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pair_to_core_proto_goTypes,
		DependencyIndexes: file_pair_to_core_proto_depIdxs,
		MessageInfos:      file_pair_to_core_proto_msgTypes,
	}.Build()
	File_pair_to_core_proto = out.File
	file_pair_to_core_proto_goTypes = nil
	file_pair_to_core_proto_depIdxs = nil
}
