//**************************************************************
//Service mode proto file
//- command/response definition
//**************************************************************

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v3.21.12
// source: service_mode.proto

package ned

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SetServiceModeStatusRequestPayload struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	IsServiceModeOn bool                   `protobuf:"varint,1,opt,name=is_service_mode_on,json=isServiceModeOn,proto3" json:"is_service_mode_on,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SetServiceModeStatusRequestPayload) Reset() {
	*x = SetServiceModeStatusRequestPayload{}
	mi := &file_service_mode_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetServiceModeStatusRequestPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetServiceModeStatusRequestPayload) ProtoMessage() {}

func (x *SetServiceModeStatusRequestPayload) ProtoReflect() protoreflect.Message {
	mi := &file_service_mode_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetServiceModeStatusRequestPayload.ProtoReflect.Descriptor instead.
func (*SetServiceModeStatusRequestPayload) Descriptor() ([]byte, []int) {
	return file_service_mode_proto_rawDescGZIP(), []int{0}
}

func (x *SetServiceModeStatusRequestPayload) GetIsServiceModeOn() bool {
	if x != nil {
		return x.IsServiceModeOn
	}
	return false
}

var File_service_mode_proto protoreflect.FileDescriptor

const file_service_mode_proto_rawDesc = "" +
	"\n" +
	"\x12service_mode.proto\x12\x03ned\"Q\n" +
	"\"SetServiceModeStatusRequestPayload\x12+\n" +
	"\x12is_service_mode_on\x18\x01 \x01(\bR\x0fisServiceModeOnB\x11Z\x0fpooltester3/nedb\x06proto3"

var (
	file_service_mode_proto_rawDescOnce sync.Once
	file_service_mode_proto_rawDescData []byte
)

func file_service_mode_proto_rawDescGZIP() []byte {
	file_service_mode_proto_rawDescOnce.Do(func() {
		file_service_mode_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_service_mode_proto_rawDesc), len(file_service_mode_proto_rawDesc)))
	})
	return file_service_mode_proto_rawDescData
}

var file_service_mode_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_service_mode_proto_goTypes = []any{
	(*SetServiceModeStatusRequestPayload)(nil), // 0: ned.SetServiceModeStatusRequestPayload
}
var file_service_mode_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_service_mode_proto_init() }
func file_service_mode_proto_init() {
	if File_service_mode_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_service_mode_proto_rawDesc), len(file_service_mode_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_service_mode_proto_goTypes,
		DependencyIndexes: file_service_mode_proto_depIdxs,
		MessageInfos:      file_service_mode_proto_msgTypes,
	}.Build()
	File_service_mode_proto = out.File
	file_service_mode_proto_goTypes = nil
	file_service_mode_proto_depIdxs = nil
}
